sequenceDiagram
    participant browser
    participant server

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    activate server
    server-->>browser: 201 {content: "prueba", date: "2025-03-12T00:09:42.840Z"}
    deactivate server

    Note right of browser: The browser executes the callback function that renders the notes.